#-----------------------------
#---- INPUT CONFIGURATION ----
#-----------------------------
Input:
  labels: ["Numéro", "Nom", "Prénom"]  # mabels of the 'default' columns in the output file
  n_students: 4  # possible values: null, int (overdriven if input_from_file activated)
  import_from_file:
    activate: true  # possible values: true, false
    name_file: classe_list.xlsx  # name of the input file
    name_sheet: Classe  # name of the sheet where information is taken
    name_cols: ["Numéro", "Nom", "Prénom"]  # name of the columns to import from input file

#------------------------------
#---- OUTPUT CONFIGURATION ----
#------------------------------

name_outfile: excel_template.xlsx  # name of the output file (the templated Excel file)

Sheets:
  Classe: Classe  # name of the Classe sheet
  Grades: Notes   # name of the Grades sheet
  Remarks: Remarques  # name of the Remarks sheet
  Copy: Copie  # name of the Copy sheet
  Skills: Compétences  # name of the Skills sheet

LabelGradeColumn: Note  # name of the 'Total grade' column in the Excel file

# labels of the 3 levels of evaluation (for Copy comments and Skills)
Levels: ["Non acquis", "En voie d'acquisition", "Acquis"]

GradingScheme:
  #question_label: list of possible points for this question
  1.1: [0, 1]
  1.2: [0, 1, 2]
  1.3: [0, 0.5, 1, 1.5, 2]

Remarks:
  # dummy_key_for_the_remark:
  #   label: <Put the actual remark here>
  #   default: <Select a default value: True or False>
  #   autofill:
  #     activate: <Switch for the automatic fill: True or False>
  #     questions: <Select a list of questions linked to this remark>
  #     criteria: <Comparison to threshold value: '<', '<=', '>' or '>=' >
  #     threshold: <Threshold value to switch on/off the remark: a float>
  remark1:
    label: "Poursuivez vos efforts !"
    default: False
    autofill:
      activate: True
      questions: [1.2]  # TODO add a "enforce list in code in case there is only one question"
      criteria: <
      threshold: 0.5
  remark2:
    label: "Ceci est une remarque"
    default: null
    autofill:
      activate: False

Copy:
  # dummy_key_for_the_comment
  #   label: <Put the actual remark here>
  #   default: <Select a default value: null or a 'Levels' entry>
  comment1:
    label: "Soin"
    default: null
  comment2:
    label: "Mise en évidence des résultats"
    default: null
  comment3:
    label: "Numérotation des pages"
    default: "Acquis"

Skills:
  # dummy_key_for_the_skill:
  #   label: <Put the actual skill here>
  #   default: <Select a default value: null or a 'Levels' entry>
  #   autofill:
  #     activate: <Switch for the automatic fill: True or False>
  #     questions: <Select a list of questions linked to this skill>
  #     threshold: <Threshold values: a list of two floats such as [thr1, thr2]:
  #                 below thr1, Levels[0] is set;
  #                 between thr1 and thr2, Levels[1] is set;
  #                 above thr2, Levels[2] is set>
  skill1:
    label: "Skill number 1"
    default: null
    autofill:
      activate: True
      questions: [1.1 ,1.2]  # TODO add a "enforce list in code in case there is only one question"
      thresholds: [0.4, 0.8]

  skill2:
    label: "Skill number 2"
    default: "Non acquis"
    autofill:
      activate: False
